configs:
  modulesFolder: /home/jycouet/udev/gh/my-minion-mr/packages/main/src/lib/modules
  moduleOutputFolder: _gen
  outputFolder: /home/jycouet/udev/gh/my-minion-mr/packages/main/src/lib/graphql/_gen

actions:
  # - createBaseStructure: true
  createEnumsModule:
    prismaFile: /home/jycouet/udev/gh/my-minion-mr/packages/main/prisma/schema.prisma
    importBaseTypesFrom: $graphql/_gen/graphqlTypes

  mergeModuleTypedefs: true
  mergeModuleResolvers: true
  mergeContexts: true
  mergeModules: true
