generates:
  apps/firstApp/src/lib/graphql/_gen:
    modules:
      - apps/firstApp/src/lib/modules/*
      - packages/modules/*(user)
    actions:
      createEnumsModule:
        prismaFile: apps/firstApp/prisma/schema.prisma
        enumsModuleFolder: /home/jycouet/udev/gh/my-minion-mr/apps/capa/src/lib/modules
      mergeModuleTypedefs: true
      mergeModuleResolvers: true
      mergeContexts: false
      mergeModules: true

    moduleOutputFolder: _gen
    importBaseTypesFrom: $graphql/_gen/graphqlTypes
