generates:
  -apps/firstApp/src/lib/graphql/_gen:
    outputFolder: _gen
    importBaseTypesFrom: $graphql/_gen/graphqlTypes
    modules:
      - apps/firstApp/src/lib/modules/*
      - packages/modules/*(user)
    actions:
      createEnumsModule:
        prismaFile: apps/firstApp/prisma/schema.prisma
      mergeModuleTypedefs: true
      mergeModuleResolvers: true
      mergeContexts: true
      mergeModules: true
