configs:
  modulesFolder: ./src/lib/modules
  moduleOutputFolder: _kitql
  outputFolder: ./src/lib/graphql/_kitql

actions:
  mergeModuleTypedefs: true
  mergeModuleResolvers: true
  mergeContexts: true
  mergeModules: true
