name: Release

on:
  push:
    branches:
      - main

jobs:
  stable:
    name: stable
    runs-on: ubuntu-latest
    environment: Publishing
    steps:
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=$NPM_EMAIL
            name=$NPM_NAME
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_NAME: ${{ secrets.NPM_NAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing to NPM
        uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
        with:
          releaseScript: release
          nodeVersion: 17
          packageManager: pnpm
        secrets:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          npmToken: ${{ secrets.NPM_TOKEN }}
